# Nome do Workflow da GitHub Action
name: Generate Snake Animation

# Controles de quando a Action será executada
on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você execute a Action manualmente pela aba Actions
  workflow_dispatch:

# Tarefas que a Action vai executar
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Usa uma Action pré-pronta chamada 'platane/snk'
      - name: Generate Snake
        uses: platane/snk@v3
        with:
          # ID do seu usuário do GitHub. O ${{ github.repository_owner }} pega automaticamente.
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de saídas que serão geradas. O padrão é a animação da cobrinha.
          # O arquivo será salvo na branch 'output' com o nome 'github-contribution-grid-snake.svg'
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark

      # Passo 2: Envia o arquivo gerado para o repositório
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output # O nome da branch onde a imagem será salva
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
